### ISSUE TITLE
Putty parameter -load cannot work properly with ConEmu

### ISSUE THREAD

**Issue by Maximus5** [Maximus5/conemu-old-issues#1211]
Originally reported on Google Code with ID 1211

```
OS version: WinXP SP3 x86
ConEmu version: 130815(32)


*Bug description*
Putty parameter -load cannot work properly with ConEmu


*What I want*
With putty parameter -load, I want one click to open a new putty session in ConEmu.



*Steps to reproduction*
1.New Tasks named "PuttyTest" for example
2.commands: D:\Sync\Software\putty\putty.exe -new_console -load "you putty session
alias name" 
3.When click this task from PLUS SIGN, new session won't appear in ConEmu but the seperate
putty windows out of ConEmu. (Please see attached screenshot)


If you want me to reply you as soon as possible, please send email to lipeizhengcn@qq.com

Thanks. You guys are really doing the amazing thing. 


```

Reported by `lipeizhengcn` on 2013-08-28 03:41:41

<hr>
- _Attachment: [2013-08-28_11-36-12.gif](https://storage.googleapis.com/google-code-attachments/conemu-maximus5/issue-1211/comment-0/2013-08-28_11-36-12.gif)_

**Comment by nils-ballmann** [comment]
For those who end up here even with nowadays versions of ConEmu and DON'T use any piping or redirection: There may be spaces in paths which need enclosing in double quotes.

BAD, but irritatingly still works through 'cmd', with external putty window:
C:\Program Files\sshTools\putty.exe -load "profilename"

GOOD:
"C:\Program Files\sshTools\putty.exe" -load "profilename"
