### ISSUE TITLE
Close button on Tab

### ISSUE THREAD

**Issue by Maximus5** [Maximus5/conemu-old-issues#1738]
Originally reported on Google Code with ID 1739

```
OS version: Win7 x64
ConEmu version: 140923

*Concept: Close Tab Button*
I hope each tab has close button("x") and user can close by single action, which configured
button action from the settings.





```

Reported by `fmiura1125` on 2014-10-03 05:49:13

**Comment by mikofski** [comment]
:+1: I would love this also, as would probably many former console2 users. meta-alt-del works fine tho.
