### ISSUE TITLE
Task Icons on tab bar don't support PNG icon transparency

### ISSUE THREAD

**Issue by Maximus5** [Maximus5/conemu-old-issues#1758]
Originally reported on Google Code with ID 1759

```
OS version: Win8.1 x64
ConEmu version: 141013 alpha
Far version (if you are using Far Manager): N/A

When specifying an icon to be used in for a task group the icon is loaded correctly,
but transparent areas of the icon are treated as black instead of the correct alpha
transparency values. The issue doesn't affect the same icons in the Jump-list, just
the icons on the tabs

*Steps to reproduction*
1. Create a task where the icon has a 32-bit (PNG + Alpha) icon present
2. Launch the task
3. Observe that the transparent regions of the icon are black


```

Reported by `clickheretoemailjohn` on 2014-10-14 11:19:01

<hr>
- _Attachment: conemu-iconbug-1.png<br>![conemu-iconbug-1.png](https://storage.googleapis.com/google-code-attachments/conemu-maximus5/issue-1759/comment-0/conemu-iconbug-1.png)_
- _Attachment: conemu-iconbug-2.png<br>![conemu-iconbug-2.png](https://storage.googleapis.com/google-code-attachments/conemu-maximus5/issue-1759/comment-0/conemu-iconbug-2.png)_

**Comment by tonyn4444** [comment]
Any update on this?

**Comment by examinedliving** [comment]
Plus 1 - tried with a simple one color circle to test.
![cmder](https://user-images.githubusercontent.com/3099093/35229756-34864c30-ff62-11e7-9108-d5e8f85a9cf5.jpg)

**Comment by Maximus5** [comment]
This is deprecated issue tracker. There is already an issue on current tracker.
