### ISSUE TITLE
Перевод программы на русский язык

### ISSUE THREAD

**Issue by Maximus5** [Maximus5/conemu-old-issues#1826]
Originally reported on Google Code with ID 1827

```
Required information!
OS version: Win7 SP1 x64
ConEmu version: 141126 preview
Far version (if you are using Far Manager): not using


Будет ли поддержка русского языка?
Или хотя-бы поддержка языковых файлов для того, чтобы пользователи сами могли переводить.
```

Reported by `Capoeiristo` on 2014-11-29 16:51:36

**Comment by Capoeirista** [comment]
Добавьте пожалуйста поддержку русского языка.

**Comment by gitkiselev** [comment]
Как выставить русский язык вместо иероглифов?

**Comment by Maximus5** [comment]
Чего? Каких иероглифов?

**Comment by gitkiselev** [comment]
Непонятные символы сбитая кодировка. PowerShell, cmd через conemu работают - русский язык отображается корректно. Сам git BASH работает корректно. Не работает русский язык имеено git BASH через conemu (161206). Все это произошло после того как слелал сброс (по сути переустановил) Windows 10 x64. Установил соответственно новый git 2.11.0. Пробовал старые версии conemu - русский не отображается. NodeJS поставил 6.9.2 LTS. Советы google yandex stackoverflow не помогли исправить ситуацию. Подскажите как исправить, буду очень благодарен. Имя пользователя компьютера латинские буквы.

**Comment by Maximus5** [comment]
И при чем здесь issue о локализации интерфейса самого ConEmu?

RTFM: https://conemu.github.io/en/UnicodeSupport.html

**Comment by MVoz** [comment]
поддерживаю, на счет русс.локализации, она как бы есть и в тоже время ...
посмотрел изменения, активно добавляется китайский, а русский нет
и не совсем ясно как активировать локализацию, писать отдельный батник для запуска?
как временное решение, я интегрировал в експлорер и в параметрах запуска указал lang
как второе решение изменить ярлык запуска
"C:\Program Files\ConEmu\ConEmu64.exe" -lng "ru"

**Comment by Maximus5** [comment]
1. Не стоит писать в **old**-issues
2. Любой пользователь может помочь в локализации, push-request приветствуются
3. В планах вынести в настройку, когда уровень локализации станет приемлемым

**Comment by MVoz** [comment]
гугол привел сюда) так же пользуюсь вашим творением уже давно
примите мои благодарности, отличная оболочка

и чуть не в тему, у меня дополнительно установлен Clink v0.4.8
при его запуске в ConEmu он не запускается 
мешает команда в CmdInit.cmd
rem cmd /d /c ver | "%windir%\system32\find.exe" "Windows"

я ее закоментировал и скрипт норм инициализирует, ОС стоит Windows 10 x64 инсайдер сборка

**Comment by Maximus5** [comment]
Ну, если в clink ошибка - нужно писать его автору.
