### ISSUE TITLE
Start PuTTY in Full Screen

### ISSUE THREAD

**Issue by Maximus5** [Maximus5/conemu-old-issues#1917]
Originally reported on Google Code with ID 1919

```
Required information!
OS version: Win7 x64
ConEmu version: ConEmu x64 150224.x64
Far version (if you are using Far Manager): N/A

Related: https://code.google.com/p/conemu-maximus5/issues/detail?id=691

By default, PuTTY is restricted in size due to the Child Window not re-sizing with
ConEmu. I noticed this can be remedied but switching PuTTY to Full Screen (Child system
menu... > Full Screen). Is there a way to automatically trigger this when opening a
PuTTY task? (Note: currently I have the Alt+Enter option turned on in PuTTY to toggle
Full Screen)

... or is there a fix for the child window re-sizing issue in the near future?

```

Reported by `gogetter333` on 2015-02-26 06:34:59

**Comment by DennisGaida** [comment]
This is possible with ExtraPuTTY (http://www.extraputty.com/) which is a fork of PuTTY. Unfortunately PuTTY does not allow saving the full screen state.

My current workaround for ConEmu is to have a keyboard shortcut for the child system menu, quickly go for "Full Screen" with the keyboard and finally make make PuTTY within ConEmu full size with ALT+ENTER.
