### ISSUE TITLE
Keyboard shortcuts are not working with different language layouts

### ISSUE THREAD

**Issue by art-and-co** [Maximus5/conemu-old-issues#1979]
In my case I have enabled quake mode. When I switch to different layout (for example to Russian) it ignores Ctrl+'; however, when switch back to English it is OK.

Thanks.

**Comment by Maximus5** [comment]
All complaints must be addressed to Microsoft and their system of globally registered hotkeys!

Especially for users with that problem there is the `Minimize/Restore (alternative)` hotkey. Set it up for second layout.

**Comment by Maximus5** [comment]
Have you mentioned the name of the project? Your issue will be deleted.
