### ISSUE TITLE
Некоректная прорисовка PuTTY.org.ru 0.66-RU-16 в ConEmu 150813f[64]

### ISSUE THREAD

**Issue by TestUser013** [Maximus5/conemu-old-issues#1982]
ConEmu неправильно прорисовывает вывод окна PuTTY.
Вот так выглядит окно http://ipic.su/img/img7/fs/puty.1450512620.png
Вот так выглядит вывод через ConEmu http://ipic.su/img/img7/fs/conemu.1450512606.png
Версия ОС Win 7 x64.

Дамп: http://rghost.ru/7xHpTrqbD

ps: понимаю что эта модификация PuTTY не очень популярная, но в ней есть нужній мне функционал.

**Comment by Maximus5** [comment]
151217

**Comment by TestUser013** [comment]
Ого, не ожидал столь быстрой реакции. Спасибо :)
В версии 151217 получается так, что прорисовка содержимого окна всегда в координатах (0,0), не зависимо от того куда перетянуть окно conemu
http://ipic.su/img/img7/fs/1.1450534490.png
http://ipic.su/img/img7/fs/2.1450534549.png

Дамп http://rghost.ru/7fPvpJDwz

**Comment by Maximus5** [comment]
Репортить ошибку автору этого форка PuTTY. ConEmu **не занимается** отрисовкой [дочерних GUI](https://conemu.github.io/en/ChildGui.html) приложений. Вообще.

**Comment by TestUser013** [comment]
Ну извиняйте, в Вашем FAQ написано что может отрисовать http://www.conemu.ru/ru/ConEmuFAQ.html#q-conemu-gui
А если не может - написано создать новый Issue с описанием и т.п. http://www.conemu.ru/ru/ConEmuFAQ.html#q-3

Жалко конечно, что ничего не выйдет с этим форком  PuTTY, ConEmu просто замечательная программа и они отлично бы дополняли друг друга (в моем случаи).

Спасибо Вам огромное за работу над ConEmu (это не сарказм). И спасибо за уделенное время.

**Comment by Maximus5** [comment]
В FAQ нет ни слова про "отрисовать". Приложение можно "поместить" в окно ConEmu. Если оно глючит - ConEmu на это повлиять никак не может. Слово "некоторые" в FAQ не просто упомянуто. Читать маны

* http://conemu.github.io/en/ChildGui.html
* http://conemu.github.io/ru/Delusions.html
* http://conemu.github.io/en/ConsoleApplication.html
