### ISSUE TITLE
WinKey+Shift+Left/Right doesn't move monitors in Quake style

### ISSUE THREAD

**Issue by JesseOlmer** [Maximus5/conemu-old-issues#1984]
ConEmu 150813g 64bit. Portable exe mode.

With ConEmu running in Quake-style drop-down mode the windows shortcut to move between monitors does not work.

Workaround:
Change settings to disable Quake-style mode, move monitors (by click-and-drag or by keyboard shortcut) and then re-enable Quake-style in settings.

**Comment by veremenko-y** [comment]
+1 Have the same behaviour

**Comment by Maximus5** [comment]
This project is read-only. Old-issues!
