### ISSUE TITLE
Quake Mode should support auto-hide on loose focus

### ISSUE THREAD

**Issue by Maximus5** [Maximus5/conemu-old-issues#592]
Originally reported on Google Code with ID 592

```
Ideally, I'd like two new options related to Quake mode:

Option 1 is to go more transparent when focus is lost, so I can leave the quake console
always on top, but set it to fade to like 20% when it doesn't have focus.

Option 2 is to automatically hide when focus is lost, so I always have to press the
hotkey to activate it and when I alt-tab or click off, it slides out of the way.

```

Reported by `jaykul@huddledmasses.org` on 2012-06-13 18:40:50

**Comment by Mpdreamz** [comment]
Sorry to revive an old thread but is it possible to also allow this checkbox to be checked when not enabling quake style slidedowns?

I have `CTRL+backtick` setup to bring conemu into fullscreen view with `always on top` checked. This is slightly different then quake style which is not fullscreen and because i disabled all animations is considerably slower to show then just the fullscreen and `always on top` combo. 

What I miss from that combo though is that while active, `alt+tab` or switching virtual desktops does not auto hide the fullscreen conemu window.

**Comment by Maximus5** [comment]
It looks like you are talking about different configurations. So I don't understand your problem.

https://conemu.github.io/en/ConEmuXml.html

**Comment by avielc** [comment]
Another revive I have to apologize for, 
But this is an idea that I believe could be great!
@Maximus5 - is it possible to add a delay for the conemu to disappear after XXX time? 
That way, if I jump over to a text pad to copy some information to paste into an ssh console, it won't disappear but if I go around surfing the net after let's say 5 second it would disappear. 
that way you have a solution of both sides of the coin. 
(also defining a hotkey to toggle "auto-hide when loose focus" - can be a manual solution for such case, to decide when to have it active or inactive)

Thanks again for all your work, this is an amazing tool!
Except for some issues I have on Windows 10 - bash environment - vi\nano -centos systms, it works amazingly well!

Thanks again

**Comment by maxime4000** [comment]
Hi, I like the idea of auto-hide on loose focus, but sometime, I want it to stay briefly on screen while I'm doing something else. Could there be a option to add a delay before it's get hidden ? Like if I want it to hide immediately I do the shortcut twice and if not, it wait and hide in X timeout define by the users. Ex : When it loose focus, it wait like 10000 ms and hide automatically after that delay and if I need it back, i just have to click on the console to keep it there. 

Thanks
Note: Maybe this should be ask in a new issues but I though it was more direct writing it down here.
Edit: My bad the message before ask the same thing. But I think it's a great idea haha
