### ISSUE TITLE
Symantec reports trojan in setup file

### ISSUE THREAD

**Issue by Maximus5** [Maximus5/conemu-old-issues#729]
Originally reported on Google Code with ID 729

```
OS version: Win7 x64
ConEmu version: 120926
Far version (if you are using Far Manager): -

Symantec reports trojan in installer.
```

Reported by `simendsjo` on 2012-09-27 05:55:57

<hr>
- _Attachment: [symantec_ws-reputation-1.jpg](https://storage.googleapis.com/google-code-attachments/conemu-maximus5/issue-729/comment-0/symantec_ws-reputation-1.jpg)_

**Comment by AndrewBragdon** [comment]
ConEmu is now getting flagged by Windows Defender as having Win32/Peals.F!cl

What is that?

**Comment by Maximus5** [comment]
https://conemu.github.io/en/FalseAlarms.html

Check VirusTotal
https://www.virustotal.com/#/file/1af1a0ae15b5ceeaacaa93197182e634c502162c178dc15afaa461b4b93dde37/detection
